//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Resources/InteractionSystem/InputActionAssets/OpenXRInput/OpenXRInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputActionAssetCode
{
    public partial class @OpenXRInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @OpenXRInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""OpenXRInput"",
    ""maps"": [
        {
            ""name"": ""LeftController"",
            ""id"": ""def5955f-669f-4edc-b0fd-bdb341743af5"",
            ""actions"": [
                {
                    ""name"": ""TriggerButton"",
                    ""type"": ""Button"",
                    ""id"": ""cb75d90c-aee6-4c73-9a7b-d1af2e503f15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerFloat"",
                    ""type"": ""Value"",
                    ""id"": ""5967ad10-4659-4716-86dc-c948e2d13061"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripButton"",
                    ""type"": ""Button"",
                    ""id"": ""375ee60f-8171-4d9a-8cac-94748af09473"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripFloat"",
                    ""type"": ""Value"",
                    ""id"": ""07284602-bc3f-4a92-bbf8-0c88d5654cc0"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""aa3faebb-38f0-4688-aaf1-000db608106b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""51ce6c1b-e66c-4d2b-bc8a-43f4d73b3db3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""eb67eca1-c42d-4e8c-8e5c-ffbe8c36569d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""84039a4a-07fe-4a80-ad99-3ff32e3b488f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""4447259f-cd4b-4063-8e32-e796149604f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Thumbstick"",
                    ""type"": ""Value"",
                    ""id"": ""494db0d9-188a-4e03-b45a-da3069affa55"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThumbstickTouched"",
                    ""type"": ""Button"",
                    ""id"": ""bf9e3b93-5c3d-4c00-978d-3857949096b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickClicked"",
                    ""type"": ""Button"",
                    ""id"": ""980d4122-8815-48ed-844f-4a8534ba2beb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SystemButton"",
                    ""type"": ""Button"",
                    ""id"": ""9f32d138-8f12-4e69-9964-fd6f1b21f55b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SystemButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""e0ddf16f-f6b0-4fde-b661-91870b28cdbf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a1e4dbe6-500d-4413-a05a-799eaf2c09f3"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebd0b931-6c4d-4cf5-80e4-6c0198c94314"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerFloat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1c90332-1b9d-4e6c-b546-0819e8a120ad"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70792b10-d155-44d7-9983-b9a232574ace"",
                    ""path"": ""<XRController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripFloat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25dd0c04-c564-4c1d-bb71-2f103baeb46b"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""901ef6c9-0f11-45bc-b6ae-cd98f4abbdc1"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bea74aa0-9408-4526-82e7-cbf9f8623fbe"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edeb87ed-605c-4d40-a74d-236649da506f"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f813138-7007-4d5b-96fd-547b8cdb93ff"",
                    ""path"": ""<XRController>{LeftHand}/menuButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b92ac16-8ee3-4757-b1c1-ce20e6a46138"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thumbstick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21114d6a-09d1-4113-bacb-6e8f0a98151d"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""669b95d9-bd20-4f18-953c-8f8ddad689b1"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1146934-924b-41b3-81e3-cc4f1c28909f"",
                    ""path"": ""<XRController>{LeftHand}/system"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SystemButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46854ebb-4b25-4f48-b7cb-99a6c3cb89d1"",
                    ""path"": ""<XRController>{LeftHand}/systemTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SystemButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RightController"",
            ""id"": ""76b2c382-e885-4b34-820c-cf274d7904a7"",
            ""actions"": [
                {
                    ""name"": ""TriggerButton"",
                    ""type"": ""Button"",
                    ""id"": ""18a6f21e-7ea3-4c4a-9f3d-39d29e811a43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerFloat"",
                    ""type"": ""Value"",
                    ""id"": ""91b5735c-49b2-467a-9c8b-0206c4c78b08"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripButton"",
                    ""type"": ""Button"",
                    ""id"": ""0b36781a-fd51-4577-852d-910b0ec60abe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripFloat"",
                    ""type"": ""Value"",
                    ""id"": ""6f8d652c-0518-49c7-8649-5b1dc94e2be8"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""dc25d446-2bd4-474e-9a2d-9f2c8b6e9130"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""8abf6a54-5481-4167-a7a3-70c7af35ca88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""1f31c5a5-5b21-4d21-b639-313ec8c14488"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""a43b42fd-4b41-46bb-b8e3-335323b1cb0b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuButton"",
                    ""type"": ""Button"",
                    ""id"": ""f162a31e-4f91-410b-a4ba-5d28759c9eec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Thumbstick"",
                    ""type"": ""Value"",
                    ""id"": ""d41fc995-d4f8-4f80-8fae-e48d1cec02bd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThumbstickTouched"",
                    ""type"": ""Button"",
                    ""id"": ""7ad817dd-0d22-456c-b935-d7126338e97a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickClicked"",
                    ""type"": ""Button"",
                    ""id"": ""1fcd0188-f4c7-409c-a16c-f46d2919189c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SystemButton"",
                    ""type"": ""Button"",
                    ""id"": ""a5711417-320b-4274-bf39-7502314f90c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SystemButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""4cc11b73-4584-4420-a9cb-7cecc993d46f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0de1c107-baac-4826-833c-e59256976251"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdbde773-d3b3-4192-8739-f9ef6128e28b"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerFloat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d201f431-3277-46e4-83c1-7ddbd8e07927"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34ea9c20-f92c-4e0f-966d-51e42d61c7c5"",
                    ""path"": ""<XRController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripFloat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7466827e-46ce-44ef-98d6-fec1280ab3fe"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39319486-6274-4710-8532-ee99668721fd"",
                    ""path"": ""<XRController>{RightHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aee5403-243a-448f-8039-33d0812576e6"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc19eb24-9c1a-4b5c-a0bf-2adceafe1970"",
                    ""path"": ""<XRController>{RightHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""027cc04a-bec3-49dd-af82-4c79a9dc457d"",
                    ""path"": ""<XRController>{RightHand}/menuButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6edacfd-ab27-4a14-b14d-7e44c9daf7cc"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Thumbstick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8787dc5b-3346-407f-83d2-4fa40cad81fc"",
                    ""path"": ""<XRController>{RightHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""032dd1a1-73c0-4cd5-bb2a-d71b4170092f"",
                    ""path"": ""<XRController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e99b9d76-ab7b-46bf-8180-088edef200d5"",
                    ""path"": ""<XRController>{RightHand}/system"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SystemButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02528950-da38-4636-9b96-6af5595ffa0e"",
                    ""path"": ""<XRController>{RightHand}/systemTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SystemButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // LeftController
            m_LeftController = asset.FindActionMap("LeftController", throwIfNotFound: true);
            m_LeftController_TriggerButton = m_LeftController.FindAction("TriggerButton", throwIfNotFound: true);
            m_LeftController_TriggerFloat = m_LeftController.FindAction("TriggerFloat", throwIfNotFound: true);
            m_LeftController_GripButton = m_LeftController.FindAction("GripButton", throwIfNotFound: true);
            m_LeftController_GripFloat = m_LeftController.FindAction("GripFloat", throwIfNotFound: true);
            m_LeftController_PrimaryButton = m_LeftController.FindAction("PrimaryButton", throwIfNotFound: true);
            m_LeftController_PrimaryButtonTouched = m_LeftController.FindAction("PrimaryButtonTouched", throwIfNotFound: true);
            m_LeftController_SecondaryButton = m_LeftController.FindAction("SecondaryButton", throwIfNotFound: true);
            m_LeftController_SecondaryButtonTouched = m_LeftController.FindAction("SecondaryButtonTouched", throwIfNotFound: true);
            m_LeftController_MenuButton = m_LeftController.FindAction("MenuButton", throwIfNotFound: true);
            m_LeftController_Thumbstick = m_LeftController.FindAction("Thumbstick", throwIfNotFound: true);
            m_LeftController_ThumbstickTouched = m_LeftController.FindAction("ThumbstickTouched", throwIfNotFound: true);
            m_LeftController_ThumbstickClicked = m_LeftController.FindAction("ThumbstickClicked", throwIfNotFound: true);
            m_LeftController_SystemButton = m_LeftController.FindAction("SystemButton", throwIfNotFound: true);
            m_LeftController_SystemButtonTouched = m_LeftController.FindAction("SystemButtonTouched", throwIfNotFound: true);
            // RightController
            m_RightController = asset.FindActionMap("RightController", throwIfNotFound: true);
            m_RightController_TriggerButton = m_RightController.FindAction("TriggerButton", throwIfNotFound: true);
            m_RightController_TriggerFloat = m_RightController.FindAction("TriggerFloat", throwIfNotFound: true);
            m_RightController_GripButton = m_RightController.FindAction("GripButton", throwIfNotFound: true);
            m_RightController_GripFloat = m_RightController.FindAction("GripFloat", throwIfNotFound: true);
            m_RightController_PrimaryButton = m_RightController.FindAction("PrimaryButton", throwIfNotFound: true);
            m_RightController_PrimaryButtonTouched = m_RightController.FindAction("PrimaryButtonTouched", throwIfNotFound: true);
            m_RightController_SecondaryButton = m_RightController.FindAction("SecondaryButton", throwIfNotFound: true);
            m_RightController_SecondaryButtonTouched = m_RightController.FindAction("SecondaryButtonTouched", throwIfNotFound: true);
            m_RightController_MenuButton = m_RightController.FindAction("MenuButton", throwIfNotFound: true);
            m_RightController_Thumbstick = m_RightController.FindAction("Thumbstick", throwIfNotFound: true);
            m_RightController_ThumbstickTouched = m_RightController.FindAction("ThumbstickTouched", throwIfNotFound: true);
            m_RightController_ThumbstickClicked = m_RightController.FindAction("ThumbstickClicked", throwIfNotFound: true);
            m_RightController_SystemButton = m_RightController.FindAction("SystemButton", throwIfNotFound: true);
            m_RightController_SystemButtonTouched = m_RightController.FindAction("SystemButtonTouched", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // LeftController
        private readonly InputActionMap m_LeftController;
        private ILeftControllerActions m_LeftControllerActionsCallbackInterface;
        private readonly InputAction m_LeftController_TriggerButton;
        private readonly InputAction m_LeftController_TriggerFloat;
        private readonly InputAction m_LeftController_GripButton;
        private readonly InputAction m_LeftController_GripFloat;
        private readonly InputAction m_LeftController_PrimaryButton;
        private readonly InputAction m_LeftController_PrimaryButtonTouched;
        private readonly InputAction m_LeftController_SecondaryButton;
        private readonly InputAction m_LeftController_SecondaryButtonTouched;
        private readonly InputAction m_LeftController_MenuButton;
        private readonly InputAction m_LeftController_Thumbstick;
        private readonly InputAction m_LeftController_ThumbstickTouched;
        private readonly InputAction m_LeftController_ThumbstickClicked;
        private readonly InputAction m_LeftController_SystemButton;
        private readonly InputAction m_LeftController_SystemButtonTouched;
        public struct LeftControllerActions
        {
            private @OpenXRInput m_Wrapper;
            public LeftControllerActions(@OpenXRInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @TriggerButton => m_Wrapper.m_LeftController_TriggerButton;
            public InputAction @TriggerFloat => m_Wrapper.m_LeftController_TriggerFloat;
            public InputAction @GripButton => m_Wrapper.m_LeftController_GripButton;
            public InputAction @GripFloat => m_Wrapper.m_LeftController_GripFloat;
            public InputAction @PrimaryButton => m_Wrapper.m_LeftController_PrimaryButton;
            public InputAction @PrimaryButtonTouched => m_Wrapper.m_LeftController_PrimaryButtonTouched;
            public InputAction @SecondaryButton => m_Wrapper.m_LeftController_SecondaryButton;
            public InputAction @SecondaryButtonTouched => m_Wrapper.m_LeftController_SecondaryButtonTouched;
            public InputAction @MenuButton => m_Wrapper.m_LeftController_MenuButton;
            public InputAction @Thumbstick => m_Wrapper.m_LeftController_Thumbstick;
            public InputAction @ThumbstickTouched => m_Wrapper.m_LeftController_ThumbstickTouched;
            public InputAction @ThumbstickClicked => m_Wrapper.m_LeftController_ThumbstickClicked;
            public InputAction @SystemButton => m_Wrapper.m_LeftController_SystemButton;
            public InputAction @SystemButtonTouched => m_Wrapper.m_LeftController_SystemButtonTouched;
            public InputActionMap Get() { return m_Wrapper.m_LeftController; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(LeftControllerActions set) { return set.Get(); }
            public void SetCallbacks(ILeftControllerActions instance)
            {
                if (m_Wrapper.m_LeftControllerActionsCallbackInterface != null)
                {
                    @TriggerButton.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnTriggerButton;
                    @TriggerFloat.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnTriggerFloat;
                    @TriggerFloat.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnTriggerFloat;
                    @TriggerFloat.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnTriggerFloat;
                    @GripButton.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnGripButton;
                    @GripButton.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnGripButton;
                    @GripButton.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnGripButton;
                    @GripFloat.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnGripFloat;
                    @GripFloat.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnGripFloat;
                    @GripFloat.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnGripFloat;
                    @PrimaryButton.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButtonTouched.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnPrimaryButtonTouched;
                    @SecondaryButton.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButtonTouched.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSecondaryButtonTouched;
                    @MenuButton.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnMenuButton;
                    @MenuButton.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnMenuButton;
                    @MenuButton.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnMenuButton;
                    @Thumbstick.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstick;
                    @Thumbstick.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstick;
                    @Thumbstick.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstick;
                    @ThumbstickTouched.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickClicked.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstickClicked;
                    @ThumbstickClicked.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstickClicked;
                    @ThumbstickClicked.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnThumbstickClicked;
                    @SystemButton.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSystemButton;
                    @SystemButton.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSystemButton;
                    @SystemButton.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSystemButton;
                    @SystemButtonTouched.started -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSystemButtonTouched;
                    @SystemButtonTouched.performed -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSystemButtonTouched;
                    @SystemButtonTouched.canceled -= m_Wrapper.m_LeftControllerActionsCallbackInterface.OnSystemButtonTouched;
                }
                m_Wrapper.m_LeftControllerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @TriggerButton.started += instance.OnTriggerButton;
                    @TriggerButton.performed += instance.OnTriggerButton;
                    @TriggerButton.canceled += instance.OnTriggerButton;
                    @TriggerFloat.started += instance.OnTriggerFloat;
                    @TriggerFloat.performed += instance.OnTriggerFloat;
                    @TriggerFloat.canceled += instance.OnTriggerFloat;
                    @GripButton.started += instance.OnGripButton;
                    @GripButton.performed += instance.OnGripButton;
                    @GripButton.canceled += instance.OnGripButton;
                    @GripFloat.started += instance.OnGripFloat;
                    @GripFloat.performed += instance.OnGripFloat;
                    @GripFloat.canceled += instance.OnGripFloat;
                    @PrimaryButton.started += instance.OnPrimaryButton;
                    @PrimaryButton.performed += instance.OnPrimaryButton;
                    @PrimaryButton.canceled += instance.OnPrimaryButton;
                    @PrimaryButtonTouched.started += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled += instance.OnPrimaryButtonTouched;
                    @SecondaryButton.started += instance.OnSecondaryButton;
                    @SecondaryButton.performed += instance.OnSecondaryButton;
                    @SecondaryButton.canceled += instance.OnSecondaryButton;
                    @SecondaryButtonTouched.started += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled += instance.OnSecondaryButtonTouched;
                    @MenuButton.started += instance.OnMenuButton;
                    @MenuButton.performed += instance.OnMenuButton;
                    @MenuButton.canceled += instance.OnMenuButton;
                    @Thumbstick.started += instance.OnThumbstick;
                    @Thumbstick.performed += instance.OnThumbstick;
                    @Thumbstick.canceled += instance.OnThumbstick;
                    @ThumbstickTouched.started += instance.OnThumbstickTouched;
                    @ThumbstickTouched.performed += instance.OnThumbstickTouched;
                    @ThumbstickTouched.canceled += instance.OnThumbstickTouched;
                    @ThumbstickClicked.started += instance.OnThumbstickClicked;
                    @ThumbstickClicked.performed += instance.OnThumbstickClicked;
                    @ThumbstickClicked.canceled += instance.OnThumbstickClicked;
                    @SystemButton.started += instance.OnSystemButton;
                    @SystemButton.performed += instance.OnSystemButton;
                    @SystemButton.canceled += instance.OnSystemButton;
                    @SystemButtonTouched.started += instance.OnSystemButtonTouched;
                    @SystemButtonTouched.performed += instance.OnSystemButtonTouched;
                    @SystemButtonTouched.canceled += instance.OnSystemButtonTouched;
                }
            }
        }
        public LeftControllerActions @LeftController => new LeftControllerActions(this);

        // RightController
        private readonly InputActionMap m_RightController;
        private IRightControllerActions m_RightControllerActionsCallbackInterface;
        private readonly InputAction m_RightController_TriggerButton;
        private readonly InputAction m_RightController_TriggerFloat;
        private readonly InputAction m_RightController_GripButton;
        private readonly InputAction m_RightController_GripFloat;
        private readonly InputAction m_RightController_PrimaryButton;
        private readonly InputAction m_RightController_PrimaryButtonTouched;
        private readonly InputAction m_RightController_SecondaryButton;
        private readonly InputAction m_RightController_SecondaryButtonTouched;
        private readonly InputAction m_RightController_MenuButton;
        private readonly InputAction m_RightController_Thumbstick;
        private readonly InputAction m_RightController_ThumbstickTouched;
        private readonly InputAction m_RightController_ThumbstickClicked;
        private readonly InputAction m_RightController_SystemButton;
        private readonly InputAction m_RightController_SystemButtonTouched;
        public struct RightControllerActions
        {
            private @OpenXRInput m_Wrapper;
            public RightControllerActions(@OpenXRInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @TriggerButton => m_Wrapper.m_RightController_TriggerButton;
            public InputAction @TriggerFloat => m_Wrapper.m_RightController_TriggerFloat;
            public InputAction @GripButton => m_Wrapper.m_RightController_GripButton;
            public InputAction @GripFloat => m_Wrapper.m_RightController_GripFloat;
            public InputAction @PrimaryButton => m_Wrapper.m_RightController_PrimaryButton;
            public InputAction @PrimaryButtonTouched => m_Wrapper.m_RightController_PrimaryButtonTouched;
            public InputAction @SecondaryButton => m_Wrapper.m_RightController_SecondaryButton;
            public InputAction @SecondaryButtonTouched => m_Wrapper.m_RightController_SecondaryButtonTouched;
            public InputAction @MenuButton => m_Wrapper.m_RightController_MenuButton;
            public InputAction @Thumbstick => m_Wrapper.m_RightController_Thumbstick;
            public InputAction @ThumbstickTouched => m_Wrapper.m_RightController_ThumbstickTouched;
            public InputAction @ThumbstickClicked => m_Wrapper.m_RightController_ThumbstickClicked;
            public InputAction @SystemButton => m_Wrapper.m_RightController_SystemButton;
            public InputAction @SystemButtonTouched => m_Wrapper.m_RightController_SystemButtonTouched;
            public InputActionMap Get() { return m_Wrapper.m_RightController; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(RightControllerActions set) { return set.Get(); }
            public void SetCallbacks(IRightControllerActions instance)
            {
                if (m_Wrapper.m_RightControllerActionsCallbackInterface != null)
                {
                    @TriggerButton.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnTriggerButton;
                    @TriggerButton.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnTriggerButton;
                    @TriggerFloat.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnTriggerFloat;
                    @TriggerFloat.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnTriggerFloat;
                    @TriggerFloat.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnTriggerFloat;
                    @GripButton.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnGripButton;
                    @GripButton.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnGripButton;
                    @GripButton.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnGripButton;
                    @GripFloat.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnGripFloat;
                    @GripFloat.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnGripFloat;
                    @GripFloat.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnGripFloat;
                    @PrimaryButton.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButton.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnPrimaryButton;
                    @PrimaryButtonTouched.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnPrimaryButtonTouched;
                    @SecondaryButton.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButtonTouched.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSecondaryButtonTouched;
                    @MenuButton.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnMenuButton;
                    @MenuButton.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnMenuButton;
                    @MenuButton.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnMenuButton;
                    @Thumbstick.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstick;
                    @Thumbstick.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstick;
                    @Thumbstick.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstick;
                    @ThumbstickTouched.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickClicked.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstickClicked;
                    @ThumbstickClicked.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstickClicked;
                    @ThumbstickClicked.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnThumbstickClicked;
                    @SystemButton.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSystemButton;
                    @SystemButton.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSystemButton;
                    @SystemButton.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSystemButton;
                    @SystemButtonTouched.started -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSystemButtonTouched;
                    @SystemButtonTouched.performed -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSystemButtonTouched;
                    @SystemButtonTouched.canceled -= m_Wrapper.m_RightControllerActionsCallbackInterface.OnSystemButtonTouched;
                }
                m_Wrapper.m_RightControllerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @TriggerButton.started += instance.OnTriggerButton;
                    @TriggerButton.performed += instance.OnTriggerButton;
                    @TriggerButton.canceled += instance.OnTriggerButton;
                    @TriggerFloat.started += instance.OnTriggerFloat;
                    @TriggerFloat.performed += instance.OnTriggerFloat;
                    @TriggerFloat.canceled += instance.OnTriggerFloat;
                    @GripButton.started += instance.OnGripButton;
                    @GripButton.performed += instance.OnGripButton;
                    @GripButton.canceled += instance.OnGripButton;
                    @GripFloat.started += instance.OnGripFloat;
                    @GripFloat.performed += instance.OnGripFloat;
                    @GripFloat.canceled += instance.OnGripFloat;
                    @PrimaryButton.started += instance.OnPrimaryButton;
                    @PrimaryButton.performed += instance.OnPrimaryButton;
                    @PrimaryButton.canceled += instance.OnPrimaryButton;
                    @PrimaryButtonTouched.started += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled += instance.OnPrimaryButtonTouched;
                    @SecondaryButton.started += instance.OnSecondaryButton;
                    @SecondaryButton.performed += instance.OnSecondaryButton;
                    @SecondaryButton.canceled += instance.OnSecondaryButton;
                    @SecondaryButtonTouched.started += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled += instance.OnSecondaryButtonTouched;
                    @MenuButton.started += instance.OnMenuButton;
                    @MenuButton.performed += instance.OnMenuButton;
                    @MenuButton.canceled += instance.OnMenuButton;
                    @Thumbstick.started += instance.OnThumbstick;
                    @Thumbstick.performed += instance.OnThumbstick;
                    @Thumbstick.canceled += instance.OnThumbstick;
                    @ThumbstickTouched.started += instance.OnThumbstickTouched;
                    @ThumbstickTouched.performed += instance.OnThumbstickTouched;
                    @ThumbstickTouched.canceled += instance.OnThumbstickTouched;
                    @ThumbstickClicked.started += instance.OnThumbstickClicked;
                    @ThumbstickClicked.performed += instance.OnThumbstickClicked;
                    @ThumbstickClicked.canceled += instance.OnThumbstickClicked;
                    @SystemButton.started += instance.OnSystemButton;
                    @SystemButton.performed += instance.OnSystemButton;
                    @SystemButton.canceled += instance.OnSystemButton;
                    @SystemButtonTouched.started += instance.OnSystemButtonTouched;
                    @SystemButtonTouched.performed += instance.OnSystemButtonTouched;
                    @SystemButtonTouched.canceled += instance.OnSystemButtonTouched;
                }
            }
        }
        public RightControllerActions @RightController => new RightControllerActions(this);
        public interface ILeftControllerActions
        {
            void OnTriggerButton(InputAction.CallbackContext context);
            void OnTriggerFloat(InputAction.CallbackContext context);
            void OnGripButton(InputAction.CallbackContext context);
            void OnGripFloat(InputAction.CallbackContext context);
            void OnPrimaryButton(InputAction.CallbackContext context);
            void OnPrimaryButtonTouched(InputAction.CallbackContext context);
            void OnSecondaryButton(InputAction.CallbackContext context);
            void OnSecondaryButtonTouched(InputAction.CallbackContext context);
            void OnMenuButton(InputAction.CallbackContext context);
            void OnThumbstick(InputAction.CallbackContext context);
            void OnThumbstickTouched(InputAction.CallbackContext context);
            void OnThumbstickClicked(InputAction.CallbackContext context);
            void OnSystemButton(InputAction.CallbackContext context);
            void OnSystemButtonTouched(InputAction.CallbackContext context);
        }
        public interface IRightControllerActions
        {
            void OnTriggerButton(InputAction.CallbackContext context);
            void OnTriggerFloat(InputAction.CallbackContext context);
            void OnGripButton(InputAction.CallbackContext context);
            void OnGripFloat(InputAction.CallbackContext context);
            void OnPrimaryButton(InputAction.CallbackContext context);
            void OnPrimaryButtonTouched(InputAction.CallbackContext context);
            void OnSecondaryButton(InputAction.CallbackContext context);
            void OnSecondaryButtonTouched(InputAction.CallbackContext context);
            void OnMenuButton(InputAction.CallbackContext context);
            void OnThumbstick(InputAction.CallbackContext context);
            void OnThumbstickTouched(InputAction.CallbackContext context);
            void OnThumbstickClicked(InputAction.CallbackContext context);
            void OnSystemButton(InputAction.CallbackContext context);
            void OnSystemButtonTouched(InputAction.CallbackContext context);
        }
    }
}
